import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, CircleAlert, FileText, Send } from "lucide-react";
import CustomerForm from "../components/CustomerForm";
import LoanCalculator from "../components/LoanCalculator";
import LoanSchemeCard from "../components/LoanSchemeCard";
import LoadingState from "../components/feedback/LoadingState";
import { useToast } from "../components/feedback/useToast";
import { getLoanSchemes } from "../../services/loanScheme.service";
import { submitLead } from "../../services/lead.service";
import { calculateLoanDetails } from "../utils/calculations";
import { validateApplication } from "../utils/validation";

const initialForm = { customerName: "", mobileNumber: "", grossWeightGrams: "", netWeightGrams: "", purityKarat: 22, selectedPlanId: "" };
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;

const Confirmation = ({ applicationId, data, scheme, details, onReset }) => <div className="mx-auto max-w-2xl px-4 py-10 text-center sm:py-16"><span className="mx-auto grid size-18 place-items-center rounded-full bg-emerald-100 text-emerald-600 shadow-lg shadow-emerald-100"><CheckCircle2 size={38} /></span><p className="mt-5 text-xs font-bold uppercase tracking-widest text-emerald-700">Application received</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900">Application Submitted Successfully</h1><p className="mx-auto mt-3 max-w-md text-slate-600">We have received your request and will review the gold details shortly.</p><div className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white text-left shadow-xl shadow-slate-200/40"><div className="flex items-center justify-between border-b border-slate-100 bg-slate-50 px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Application ID</p><p className="mt-1 break-all font-mono text-sm font-bold text-slate-900">{applicationId}</p></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-800">SUBMITTED</span></div><div className="grid grid-cols-2 gap-px bg-slate-100"><div className="bg-white p-4"><p className="text-xs text-slate-500">Applicant</p><p className="mt-1 font-bold text-slate-900">{data.customerName}</p></div><div className="bg-white p-4"><p className="text-xs text-slate-500">Selected plan</p><p className="mt-1 font-bold text-slate-900">{scheme?.name || data.selectedPlanId}</p></div><div className="bg-white p-4"><p className="text-xs text-slate-500">Net gold weight</p><p className="mt-1 font-bold text-slate-900">{data.netWeightGrams} g · {data.purityKarat}K</p></div><div className="bg-amber-50 p-4"><p className="text-xs text-amber-700">Eligible amount</p><p className="mt-1 font-extrabold text-amber-900">{money(details.maximumEligibleLoan)}</p></div></div></div><button onClick={onReset} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-amber-500 px-5 py-3 text-sm font-bold text-white shadow-md shadow-amber-200 transition hover:bg-amber-600"><FileText size={17} /> Submit another application</button></div>;

const Home = () => {
  const [formData, setFormData] = useState(initialForm); const [errors, setErrors] = useState({}); const [schemes, setSchemes] = useState([]); const [loading, setLoading] = useState(true); const [isSubmitting, setIsSubmitting] = useState(false); const [submitted, setSubmitted] = useState(null); const { showToast } = useToast();
  useEffect(() => { const load = async () => { try { const response = await getLoanSchemes(); setSchemes(response.data ?? []); } catch { showToast("Unable to load loan schemes. Check that the API server is running.", "error"); } finally { setLoading(false); } }; load(); }, [showToast]);
  const selectedScheme = useMemo(() => schemes.find((scheme) => scheme.plan_code === formData.selectedPlanId), [schemes, formData.selectedPlanId]);
  const appliedLtv = Math.min(Number(selectedScheme?.max_ltv) || 75, 75);
  const loanDetails = useMemo(() => calculateLoanDetails(formData.netWeightGrams, formData.purityKarat, 7000, appliedLtv), [formData.netWeightGrams, formData.purityKarat, appliedLtv]);
  const onChange = ({ target: { name, value } }) => { const clean = name === "mobileNumber" ? value.replace(/\D/g, "") : value; const next = { ...formData, [name]: clean }; setFormData(next); if (errors[name]) setErrors(validateApplication(next)); };
  const onBlur = () => setErrors(validateApplication(formData));
  const selectPlan = (selectedPlanId) => { setFormData((value) => ({ ...value, selectedPlanId })); setErrors((value) => ({ ...value, selectedPlanId: undefined })); };
  const handleSubmit = async (event) => { event.preventDefault(); const nextErrors = validateApplication(formData); setErrors(nextErrors); if (Object.keys(nextErrors).length) { showToast("Please correct the highlighted fields before submitting.", "warning"); return; } setIsSubmitting(true); try { const response = await submitLead({ ...formData, purityKarat: Number(formData.purityKarat), grossWeightGrams: Number(formData.grossWeightGrams), netWeightGrams: Number(formData.netWeightGrams) }); setSubmitted({ applicationId: response.applicationId, data: formData, scheme: selectedScheme, details: loanDetails }); showToast("Loan application submitted successfully.", "success"); } catch (error) { showToast(error.response?.data?.message || "We couldn't submit your application. Please try again.", "error"); } finally { setIsSubmitting(false); } };
  if (submitted) return <Confirmation {...submitted} onReset={() => { setFormData(initialForm); setErrors({}); setSubmitted(null); }} />;
  return <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8 lg:px-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-3 sm:mb-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-700">Gold-backed finance</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl">Gold Loan Application</h1><p className="mt-2 text-sm text-slate-600 sm:text-base">Get an instant estimate based on your gold details.</p></div><div className="rounded-xl border border-emerald-100 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-800">Secure & transparent process</div></div><form onSubmit={handleSubmit}><div className="grid items-start gap-5 lg:grid-cols-5 lg:gap-6"><div className="lg:col-span-2"><CustomerForm formData={formData} errors={errors} onChange={onChange} onBlur={onBlur} /></div><div className="space-y-5 lg:col-span-3"><LoanCalculator loanDetails={loanDetails} maxLtv={appliedLtv} /><section><div className="mb-3"><h2 className="text-lg font-bold text-slate-900">Choose a loan scheme</h2><p className="mt-0.5 text-sm text-slate-500">Pick the repayment plan that fits your needs.</p></div>{loading ? <LoadingState label="Loading available loan schemes…" /> : schemes.length ? <div className="grid grid-cols-1 gap-3 md:grid-cols-2">{schemes.map((scheme) => <LoanSchemeCard key={scheme.plan_code} scheme={scheme} selectedPlanId={formData.selectedPlanId} handlePlanSelect={selectPlan} />)}</div> : <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><CircleAlert className="mr-2 inline" size={18} /> No loan schemes are currently available.</div>}{errors.selectedPlanId && <p className="mt-2 text-sm font-medium text-red-600">{errors.selectedPlanId}</p>}</section></div></div><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:mt-6 sm:p-4"><p className="mb-3 text-center text-xs text-slate-500">By submitting, you confirm that the information provided is accurate.</p><button type="submit" disabled={isSubmitting || loading || !schemes.length} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 px-5 py-3.5 text-sm font-bold text-white shadow-md shadow-amber-200 transition hover:from-amber-600 hover:to-amber-700 focus:outline-none focus:ring-4 focus:ring-amber-200 disabled:cursor-not-allowed disabled:from-slate-300 disabled:to-slate-300"><Send size={17} />{isSubmitting ? "Submitting application…" : "Submit Loan Application"}</button></div></form></div>;
};
export default Home;
