import { Gem, Phone, Scale, UserRound } from "lucide-react";

const fields = [
  { name: "customerName", label: "Customer name", placeholder: "e.g. Rahul Sharma", icon: UserRound, type: "text" },
  { name: "mobileNumber", label: "Mobile number", placeholder: "10-digit mobile number", icon: Phone, type: "tel" },
  { name: "grossWeightGrams", label: "Gross weight", placeholder: "0.00", icon: Scale, type: "number", suffix: "grams" },
  { name: "netWeightGrams", label: "Net weight", placeholder: "0.00", icon: Gem, type: "number", suffix: "grams" },
];

const CustomerForm = ({ formData, errors, onChange, onBlur }) => <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-amber-100 bg-gradient-to-r from-amber-50 to-white px-6 py-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-amber-500 text-white"><UserRound size={19} /></span><div><p className="text-[11px] font-bold uppercase tracking-widest text-amber-700">Step 1 of 2</p><h2 className="mt-0.5 text-lg font-bold text-slate-900">Customer & gold details</h2><p className="mt-1 text-xs text-slate-500">Enter the applicant and collateral information.</p></div></div></div><div className="space-y-5 p-6 sm:p-7">{fields.map(({ name, label, placeholder, icon: Icon, type, suffix }) => <label key={name} className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><div className="relative"><span className="pointer-events-none absolute inset-y-0 left-0 flex w-11 items-center justify-center text-slate-400"><Icon size={18} /></span><input type={type} name={name} value={formData[name]} onChange={onChange} onBlur={onBlur} placeholder={placeholder} maxLength={name === "mobileNumber" ? 10 : undefined} min={type === "number" ? "0" : undefined} step={type === "number" ? "0.01" : undefined} inputMode={type === "number" ? "decimal" : undefined} className={`w-full rounded-xl border bg-slate-50 py-3 pl-12 text-sm outline-none transition placeholder:text-slate-400 focus:bg-white ${suffix ? "pr-20" : "pr-3"} ${errors[name] ? "border-red-400 ring-3 ring-red-100" : "border-slate-200 hover:border-slate-300 focus:border-amber-500 focus:ring-3 focus:ring-amber-100"}`} />{suffix && <span className="pointer-events-none absolute inset-y-0 right-0 flex w-18 items-center justify-center text-xs font-semibold text-slate-400">{suffix}</span>}</div>{errors[name] && <p className="mt-1.5 text-xs font-medium text-red-600">{errors[name]}</p>}</label>)}<label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">Gold purity</span><select name="purityKarat" value={formData.purityKarat} onChange={onChange} onBlur={onBlur} className={`w-full rounded-xl border bg-slate-50 px-3.5 py-3 text-sm outline-none transition focus:bg-white ${errors.purityKarat ? "border-red-400 ring-3 ring-red-100" : "border-slate-200 hover:border-slate-300 focus:border-amber-500 focus:ring-3 focus:ring-amber-100"}`}><option value={18}>18K gold</option><option value={22}>22K gold</option><option value={24}>24K gold</option></select>{errors.purityKarat && <p className="mt-1.5 text-xs font-medium text-red-600">{errors.purityKarat}</p>}</label></div></section>;

export default CustomerForm;
